-- ===========================================
-- TOKO KOPI KHALEED - DATABASE SCHEMA
-- ===========================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ===========================================
-- TABLE: profiles (User data)
-- ===========================================
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
  full_name TEXT,
  whatsapp_number TEXT,
  avatar_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- Enable RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Policy: Users can read their own profile
CREATE POLICY "Users can view own profile" ON public.profiles
  FOR SELECT USING (auth.uid() = id);

-- Policy: Users can update their own profile
CREATE POLICY "Users can update own profile" ON public.profiles
  FOR UPDATE USING (auth.uid() = id);

-- Trigger: Auto-create profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url)
  VALUES (NEW.id, NEW.raw_user_meta_data->>'full_name', NEW.raw_user_meta_data->>'avatar_url');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- ===========================================
-- TABLE: products (Menu items)
-- ===========================================
CREATE TABLE public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT CHECK (category IN ('coffee', 'non-coffee', 'heavy-meal', 'snack')),
  price INTEGER NOT NULL,
  description TEXT,
  image_url TEXT,
  is_available BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- Enable RLS (public read)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Products are viewable by everyone" ON public.products
  FOR SELECT USING (TRUE);

-- ===========================================
-- TABLE: orders (Transactions)
-- ===========================================
CREATE TABLE public.orders (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id UUID REFERENCES public.profiles,
  total_amount INTEGER NOT NULL,
  status TEXT CHECK (status IN ('pending', 'paid', 'preparing', 'completed', 'cancelled')) DEFAULT 'pending',
  dining_option TEXT CHECK (dining_option IN ('dine-in', 'takeaway')) DEFAULT 'dine-in',
  payment_method TEXT,
  payment_ref_id TEXT,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- Enable RLS
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own orders" ON public.orders
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can create own orders" ON public.orders
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- ===========================================
-- TABLE: order_items (Order details)
-- ===========================================
CREATE TABLE public.order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id UUID REFERENCES public.orders NOT NULL,
  product_id BIGINT REFERENCES public.products NOT NULL,
  quantity INTEGER DEFAULT 1,
  notes TEXT
);

-- Enable RLS
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own order items" ON public.order_items
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.orders
      WHERE orders.id = order_items.order_id
      AND orders.user_id = auth.uid()
    )
  );

CREATE POLICY "Users can create own order items" ON public.order_items
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.orders
      WHERE orders.id = order_items.order_id
      AND orders.user_id = auth.uid()
    )
  );

-- ===========================================
-- TABLE: favorites (User favorites)
-- ===========================================
CREATE TABLE public.favorites (
  user_id UUID REFERENCES public.profiles NOT NULL,
  product_id BIGINT REFERENCES public.products NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
  PRIMARY KEY (user_id, product_id)
);

-- Enable RLS
ALTER TABLE public.favorites ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own favorites" ON public.favorites
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can manage own favorites" ON public.favorites
  FOR ALL USING (auth.uid() = user_id);

-- ===========================================
-- SEED DATA: Sample products
-- ===========================================
INSERT INTO public.products (name, category, price, description, image_url, is_available) VALUES
('Manuka Latte', 'coffee', 48000, 'Signature latte with premium Manuka honey', 'https://images.unsplash.com/photo-1541167760496-162955ed8a9f?auto=format&fit=crop&q=80&w=800', TRUE),
('Khaleed Cold Brew', 'coffee', 52000, '24-hour slow brew, smooth and bold', 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&q=80&w=800', TRUE),
('Espresso Tonic', 'coffee', 45000, 'Refreshing espresso with tonic water', 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=800', TRUE),
('Matcha Oat Latte', 'non-coffee', 45000, 'Premium matcha with silky oat milk', 'https://images.unsplash.com/photo-1515823064-d6e0c04616a7?auto=format&fit=crop&q=80&w=800', TRUE),
('Chocolate Hazelnut', 'non-coffee', 42000, 'Rich chocolate with hazelnut syrup', 'https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?auto=format&fit=crop&q=80&w=800', TRUE),
('Nasi Gila', 'heavy-meal', 55000, 'Spicy fried rice with all the toppings', 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&q=80&w=800', TRUE),
('Chicken Katsu Rice', 'heavy-meal', 58000, 'Crispy chicken katsu with Japanese curry', 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&q=80&w=800', TRUE),
('Truffle Fries', 'snack', 65000, 'Crispy fries with truffle oil and parmesan', 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&q=80&w=800', TRUE),
('Croffle', 'snack', 35000, 'Croissant waffle with maple syrup', 'https://images.unsplash.com/photo-1598839950887-35715ee38836?auto=format&fit=crop&q=80&w=800', TRUE);
